### ISSUE TITLE
Cache & Set values

### ISSUE THREAD

**Issue by pacoorozco** [larapacks/setting#4]
Hello,

I'm using this package to deal with my site settings, but I'm having some troubles with **cached settings**:

See this code:

```
    $site_settings = Setting::all()->toArray();

    $uno = setting()->get('zone_default_mname');

    Setting::set('zone_default_mname', 'value1');

    $dos = setting()->get('zone_default_mname');

    setting()->set('zone_default_mname', 'value2');

    $tres = setting()->get('zone_default_mname');

    dd($uno, $dos, $tres);
```

The output is:

```
  "value"

  "value"

  "value"
```

But when I see database values are changed. **Is this behaviour normal?**

**Comment by stevebauman** [comment]
Hi @pacoorozco, going to investigate. Thanks!

**Comment by pacoorozco** [comment]
Hi @stevebauman 

I correct myself, on database value is not changed, at least "updated_at" is not modified.

If you need some more feedback, please contact me.

**Comment by stevebauman** [comment]
Cache issue, fixing now. Thanks @pacoorozco!

**Comment by stevebauman** [comment]
Please update to `v1.0.5`. This was due to the `Cache::remember` method always returning the cached value until it met the expiry date.

Surprised my test cases didn't catch this though: https://github.com/larapacks/setting/blob/master/tests/SettingTest.php#L171-L179
