### ISSUE TITLE
Cannot find existing setting

### ISSUE THREAD

**Issue by mikerockett** [larapacks/setting#8]
I turned cache off (`0`), and now Setting cannot find persisted settings that do exist. `has()` returns `false` and `find()` returns `null`.

**Code:**

```php
dd(setting()->find('acc.invserial'));
```

**DB:**

![image](https://cloud.githubusercontent.com/assets/4586280/22852696/a899cc8c-f04a-11e6-9a9d-08e065c8a020.png)

**Comment by mikerockett** [comment]
Reverting b250c8a9ac6d40ccbbe0c4c946bb3d19a8ac33f5 fixes the issue.

**Comment by stevebauman** [comment]
Going to investigate this now, thanks!

**Comment by mikerockett** [comment]
I must have been out of it when I posted that, because the current code shows the change I made to the Setting file... Or did you perhaps revert a commit that changed it to `whereKey`? 😕

**Comment by stevebauman** [comment]
The commit you mentioned is the one where I removed the use of `whereKey`: https://github.com/larapacks/setting/commit/b250c8a9ac6d40ccbbe0c4c946bb3d19a8ac33f5

Are you able to try the `dev-master` branch and see if this resolves your issue?

**Comment by stevebauman** [comment]
I've released `v1.0.7`, please run `composer update`. This should be fixed for Laravel 5.4.

**Comment by mikerockett** [comment]
Thanks, works like a charm after the update. 👍

**Comment by stevebauman** [comment]
Perfect, thanks for following up @mikerockett !
